// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD12D7CaNiYrADsC3X3wtu8fTKaApRyIYQ',
    appId: '1:723851803717:android:064f6997551dbea299f72c',
    messagingSenderId: '723851803717',
    projectId: 'fireservice-003',
    databaseURL: 'https://fireservice-003-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fireservice-003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yf9T1Z9LyisQbDBOMdUhBUysZ8jGOvg',
    appId: '1:723851803717:ios:068abd96ab4c21f099f72c',
    messagingSenderId: '723851803717',
    projectId: 'fireservice-003',
    databaseURL: 'https://fireservice-003-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fireservice-003.appspot.com',
    androidClientId: '723851803717-rm1detkedgqanij3n768f9l7gtibrc1b.apps.googleusercontent.com',
    iosClientId: '723851803717-ei9lhno8e6dl00ogsiphj62h9e1ue27v.apps.googleusercontent.com',
    iosBundleId: 'com.example.docSaver',
  );
}
